# Generated by Django 4.1.3 on 2022-11-15 11:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HELBManager', '0003_rename_name_member_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='members',
            field=models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
