# Generated by Django 4.1.3 on 2022-11-15 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HELBManager', '0004_post_members_delete_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='members',
        ),
    ]
