# Generated by Django 4.1.2 on 2022-11-21 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HELBManager', '0007_task_post_tasks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='tasks',
            new_name='status',
        ),
    ]
