# Generated by Django 4.1.3 on 2022-11-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HELBManager', '0009_rename_post_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.ManyToManyField(related_name='status', to='HELBManager.status'),
        ),
    ]
