# Generated by Django 4.1.3 on 2022-11-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HELBManager', '0010_alter_project_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
