# Generated by Django 4.1.2 on 2022-12-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HELBManager', '0011_remove_project_status_delete_status_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(default='TODO;In Progress;In Revision;Done', max_length=100),
        ),
    ]
