# Generated by Django 4.1.2 on 2022-12-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HELBManager', '0013_alter_project_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtasks', models.CharField(default='SubTask 1;SubTask 2;SubTask 3', max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('project', models.ManyToManyField(related_name='project', to='HELBManager.project')),
            ],
        ),
    ]
