# Generated by Django 4.1.2 on 2022-12-11 19:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HELBManager', '0014_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assignedMember',
            field=models.ManyToManyField(related_name='member', to=settings.AUTH_USER_MODEL),
        ),
    ]
