# Generated by Django 4.1.2 on 2022-12-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HELBManager', '0017_project_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tasks',
        ),
        migrations.AddField(
            model_name='project',
            name='tasks',
            field=models.ManyToManyField(related_name='tasks', to='HELBManager.task'),
        ),
    ]
