# Generated by Django 4.1.2 on 2022-12-29 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HELBManager', '0018_remove_task_project_remove_project_tasks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assignedMember',
        ),
        migrations.AddField(
            model_name='task',
            name='assignedMember',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignedMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
