# Generated by Django 4.1.2 on 2022-12-31 19:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HELBManager', '0019_remove_task_assignedmember_task_assignedmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='creationDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='task',
            name='lastUpdateDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
