# Generated by Django 4.1.2 on 2023-01-01 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HELBManager', '0020_task_creationdate_task_lastupdatedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='subtasks',
        ),
    ]
